name: Add Community PRs to Project
on:
  schedule:
    - cron: "5 * * * *" # Hourly at 5 minutes past the hour (**:05)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Handle vocabulary Repo
      uses: subhamX/github-project-bot@v1.0.0
      with:
        ACCESS_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
        COLUMN_NAME: "In Progress"
        PROJECT_URL: https://github.com/orgs/creativecommons/projects/13
        REPO_URL: https://github.com/creativecommons/vocabulary
