name: Manage issues and pull requests in projects
on:
  workflow_dispatch:
  schedule:
    - cron: "45 * * * *" # Hourly at 45 minutes past the hour (**:45)
jobs:

  manage_issues_and_pull_requests:
    name: Manage issues and pull requests
    runs-on: ubuntu-latest
    steps:

    # https://github.com/actions/setup-python
    - name: Install Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install pipenv
      run: |
        pip install --upgrade pip
        pip install pipenv

    # https://github.com/actions/checkout
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Python dependencies
      run: |
        pipenv sync --dev --system

    - name: 'run script to move closed issues to Active Sprint: Done'
      run: |
        ./move_closed_issues.py
      env:
        ADMIN_GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}

    - name: run script to track open issues and pull requests
      run: |
        ./track_issues_and_pull_requests.py
      env:
        ADMIN_GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
