name: Normalize Repos
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight (00:00)
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
        cd normalize_repos
        pipenv sync
    - name: Export token to env and run normalize script
      run: |
        cd normalize_repos
        pipenv run python normalize_repos.py
      env:
        ADMIN_GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
    - name: Export a report of invalid issues
      uses: actions/upload-artifact@v2
      with:
        name: invalid-issue-report
        path: /tmp/invalid_issues.yml
