name: Normalize Repos
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight (00:00)
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install system dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
    - name: Install app dependencies
      run: |
        pipenv sync
    - name: Run script with token in env
      run: |
        pipenv run ./normalize_repos.py
      env:
        ADMIN_GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
    - name: Export a report of invalid issues
      uses: actions/upload-artifact@v3
      with:
        name: invalid-issue-report
        path: /tmp/invalid_issues.yml
    - uses: gautamkrishnar/keepalive-workflow@v1
      with:
        committer_username: cc-open-source-bot
        committer_email: opensource@creativecommons.org
        time_elapsed: 46
