name: Normalize Repos
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight (00:00)
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
        pipenv sync
    - name: Export token to env and run normalize script
      run: |
        pipenv run ./normalize_repos.py
      env:
        ADMIN_GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
    - name: Export a report of invalid issues
      uses: actions/upload-artifact@v2
      with:
        name: invalid-issue-report
        path: /tmp/invalid_issues.yml
    - uses: gautamkrishnar/keepalive-workflow@1.07
      with:
        committer_username: cc-open-source-bot
        committer_email: opensource@creativecommons.org
        time_elapsed: 46
