name: Push data to CC Open Source
on:
  schedule:
    - cron: '15 0 * * *' # Daily at midnight:15 (00:15)
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install system dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
    - uses: actions/checkout@v3
    - name: Install app dependencies
      run: |
        pipenv sync
    - name: Run script with tokens in env
      run: |
        pipenv run ./push_data_to_ccos.py
      env:
        ADMIN_GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
        ADMIN_ASANA_TOKEN: ${{ secrets.ADMIN_ASANA_TOKEN }}
