name: Sync Community Teams with GitHub
on:
  schedule:
    - cron: '30 0 * * *' # Daily at midnight:30 (00:30)
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
        cd sync_community_team
        pipenv sync
    - name: Export token to env and run script
      run: |
        cd sync_community_team
        pipenv run python sync_teams.py
      env:
        ADMIN_GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
        ADMIN_ASANA_TOKEN: ${{ secrets.ADMIN_ASANA_TOKEN }}
