name: Sync Community Teams with GitHub
on:
  schedule:
    - cron: '30 0 * * *' # Daily at midnight:30 (00:30)
  workflow_dispatch:

jobs:
  sync_community_teams:
    runs-on: ubuntu-latest
    steps:

    # https://github.com/actions/setup-python
    - name: Setup Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv

    # https://github.com/actions/checkout
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install app dependencies
      run: pipenv sync --system

    - name: Run script with tokens in env
      run: ./sync_community_teams.py
      env:
        ADMIN_GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
        ADMIN_ASANA_TOKEN: ${{ secrets.ADMIN_ASANA_TOKEN }}
