name: Sync Community Teams with GitHub
on:
  schedule:
    - cron: '30 0 * * *' # Daily at midnight:30 (00:30)
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install system dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
    - uses: actions/checkout@v3
    - name: Install app dependencies
      run: |
        pipenv sync
    - name: Run script with tokens in env
      run: |
        pipenv run ./sync_community_teams.py
      env:
        ADMIN_GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
        ADMIN_ASANA_TOKEN: ${{ secrets.ADMIN_ASANA_TOKEN }}
